#!/usr/bin/env bash
# scaffold.sh — Materialize the ForgeOS control-plane into the current project.
#
# Creates ./.forgeos/ holding the canonical engine (agents, instructions,
# prompts, skills, hooks, AGENTS.md, tickets.py) plus fresh per-project runtime
# state (guardian, memory-bank, ticket-state). Canonical content is always
# refreshed; runtime state is created only if absent (never clobbers progress).
#
# Safe to re-run (idempotent). Resolves its own location, so it works whether
# invoked by the /forgeos:init command, a hook, or directly.
set -euo pipefail

PLUGIN_ROOT="$(cd "$(dirname "$(realpath "${BASH_SOURCE[0]}")")/.." && pwd)"
PAYLOAD="$PLUGIN_ROOT/payload"
PROJECT="${CLAUDE_PROJECT_DIR:-$PWD}"
DEST="$PROJECT/.forgeos"

if [[ ! -d "$PAYLOAD" ]]; then
  echo "ERROR: payload not found at $PAYLOAD — is the plugin installed correctly?" >&2
  exit 1
fi

echo "ForgeOS: initializing control-plane in $DEST"
mkdir -p "$DEST"

# --- canonical (always refreshed; read-only at runtime) -----------------------
for item in agents instructions prompts skills vibecoding observability hooks; do
  if [[ -e "$PAYLOAD/$item" ]]; then
    rm -rf "$DEST/$item"
    cp -R "$PAYLOAD/$item" "$DEST/$item"
  fi
done
cp "$PAYLOAD/AGENTS.md"      "$DEST/AGENTS.md"
cp "$PAYLOAD/tickets.py"     "$DEST/tickets.py"
cp "$PAYLOAD/todo_visual.py" "$DEST/todo_visual.py"
mkdir -p "$DEST/guardian"
cp "$PAYLOAD/guardian/loop-detection-rules.md" "$DEST/guardian/loop-detection-rules.md"

# --- runtime state (created once; preserved across re-runs) -------------------
if [[ ! -f "$DEST/guardian/STOP_ALL" ]]; then
  cp "$PAYLOAD/templates/guardian/STOP_ALL" "$DEST/guardian/STOP_ALL"
fi

if [[ ! -d "$DEST/memory-bank" ]]; then
  cp -R "$PAYLOAD/templates/memory-bank" "$DEST/memory-bank"
fi

# Ticket directories + 14 SDLC stage folders (only created if missing).
mkdir -p "$DEST/tickets" "$DEST/agent-output"
for stage in READY RESEARCH PM ARCHITECT DEVOPS BACKEND UIDESIGNER FRONTEND \
             QA SECURITY CI DOCS VALIDATION DONE; do
  mkdir -p "$DEST/ticket-state/$stage"
done

# Version marker.
printf '%s\n' "forgeos-plugin v1.0.0" > "$DEST/.version"

# Friendly .gitignore hint for runtime churn (only if project is a git repo and
# no .forgeos rule exists yet). Non-destructive — appended, never overwritten.
if [[ -d "$PROJECT/.git" && -f "$PROJECT/.gitignore" ]] \
   && ! grep -q '\.forgeos/' "$PROJECT/.gitignore" 2>/dev/null; then
  {
    echo ""
    echo "# ForgeOS runtime state (engine is regenerated by the plugin on /forgeos:init)"
    echo ".forgeos/ticket-state/"
    echo ".forgeos/agent-output/"
  } >> "$PROJECT/.gitignore"
fi

echo "ForgeOS: ready. Engine + runtime state initialized under .forgeos/"
echo "Next: run /start to plan a project, or /continue to resume one."
