/** A parsed GitHub issue from the Expensify/App repo */
export interface GitHubIssue {
  id: number;
  number: number;
  title: string;
  body: string;
  html_url: string;
  state: string;
  labels: { name: string }[];
  created_at: string;
  updated_at: string;
  user: { login: string; id: number };
  comments: number;
}

/** A comment on a GitHub issue */
export interface GitHubComment {
  id: number;
  body: string;
  user: { login: string; id: number };
  created_at: string;
  updated_at: string;
}

/** A proposal generated by the agent */
export interface Proposal {
  issueNumber: number;
  issueTitle: string;
  issueUrl: string;
  body: string;
  generatedAt: string;
  model: string;
  toolCalls: number;
  filePath: string;
}

/** Tool call definition for OpenRouter/OpenAI function calling */
export interface ToolDefinition {
  type: 'function';
  function: {
    name: string;
    description: string;
    parameters: Record<string, unknown>;
  };
}

/** A tool call result to be fed back to the LLM */
export interface ToolResult {
  role: 'tool';
  tool_call_id: string;
  content: string;
}

/** Message in the OpenAI-compatible format */
export interface ChatMessage {
  role: 'system' | 'user' | 'assistant' | 'tool';
  content: string | null;
  tool_calls?: {
    id: string;
    type: 'function';
    function: { name: string; arguments: string };
  }[];
  /** Required when role is 'tool' */
  tool_call_id?: string;
}

/** Streaming chunk from OpenRouter */
export interface OpenRouterChunk {
  choices: {
    delta: { content?: string | null; tool_calls?: any[] };
    finish_reason: string | null;
  }[];
  usage?: {
    prompt_tokens: number;
    completion_tokens: number;
    reasoningTokens?: number;
  };
  error?: { message: string };
}